BEGIN;

INSERT INTO public.material_vendors (
  id,
  vendor_code,
  legal_company_name,
  company_name,
  address,
  country,
  primary_contact_person,
  material_category,
  contact_email,
  contact_tel,
  pic_user_id,
  is_default_vendor,
  bank_account_name,
  bank_account_number,
  bank_name,
  bank_code,
  bank_address,
  swift_code,
  settlement_payment_term,
  settlement_calculation_method,
  settlement_credit_days,
  settlement_advance_payment_percentage,
  settlement_balance_trigger_event,
  settlement_currency,
  settlement_prepayment_pool,
  settlement_prepayment_threshold,
  settlement_current_prepaid_balance,
  remark,
  status,
  created_at,
  updated_at
) VALUES
  (
    'dcd7d69f-9137-41aa-8f87-5d20c0c13001',
    'YQ0001',
    'Jiaxing Paint Systems Co., Ltd.',
    'JX Paint Systems',
    'No. 18 Jiali Road, Jiashan, Zhejiang',
    'China',
    'Helen Xu',
    '油漆',
    'paint@jxps.com',
    '+86 573 8888 1001',
    '7a2b2ce8-e87a-4cc0-9165-52a6996fd701',
    true,
    'Jiaxing Paint Systems Co., Ltd.',
    '6222020000111122223',
    'Agricultural Bank of China',
    'ABCJX001',
    'Jiashan, Zhejiang',
    'ABOCCNBJ320',
    'Monthly',
    'By actual consumption',
    30,
    10.00,
    'On Invoice',
    'CNY',
    false,
    0.00,
    0.00,
    'Default paint vendor for test coverage.',
    'Normal',
    '2026-04-01T18:10:00+00:00',
    '2026-04-01T18:10:00+00:00'
  ),
  (
    '5f4f6558-c670-40db-aeb0-9da332fe3002',
    'DB0001',
    'Evergreen Flooring Industrial Ltd.',
    'Evergreen Flooring',
    '99 Industry Park, Suzhou',
    'China',
    'Alan Zhou',
    '地板',
    'sales@evergreenflooring.cn',
    '+86 512 6655 2211',
    '9b2b0c18-0101-43f4-a5bf-8d9128eaa7c2',
    true,
    'Evergreen Flooring Industrial Ltd.',
    '998877665544332211',
    'China Construction Bank',
    'CCBSZ001',
    'Suzhou, Jiangsu',
    'PCBCCNBJSU',
    'Net 45',
    'By purchase order quantity',
    45,
    30.00,
    'Before Release',
    'USD',
    true,
    30000.00,
    15600.00,
    'Default flooring vendor with prepayment pool enabled.',
    'Normal',
    '2026-04-01T18:11:00+00:00',
    '2026-04-01T18:11:00+00:00'
  ),
  (
    'f1b18192-9cf1-43ad-9aa1-fdfe3bcf3003',
    'MF0001',
    'SealPro Adhesive Technologies',
    'SealPro',
    '128 Harbor Road, Ningbo',
    'China',
    'Irene Gao',
    '密封胶',
    'service@sealpro.com',
    '+86 574 2233 9898',
    null,
    false,
    null,
    null,
    null,
    null,
    null,
    null,
    'Net 20',
    'By delivered batch',
    20,
    0.00,
    'After Gate out',
    'USD',
    false,
    0.00,
    0.00,
    'Secondary material vendor example with optional PIC empty.',
    'Blocked',
    '2026-04-01T18:12:00+00:00',
    '2026-04-01T18:12:00+00:00'
  )
ON CONFLICT (vendor_code) DO UPDATE
SET
  legal_company_name = EXCLUDED.legal_company_name,
  company_name = EXCLUDED.company_name,
  address = EXCLUDED.address,
  country = EXCLUDED.country,
  primary_contact_person = EXCLUDED.primary_contact_person,
  material_category = EXCLUDED.material_category,
  contact_email = EXCLUDED.contact_email,
  contact_tel = EXCLUDED.contact_tel,
  pic_user_id = EXCLUDED.pic_user_id,
  is_default_vendor = EXCLUDED.is_default_vendor,
  bank_account_name = EXCLUDED.bank_account_name,
  bank_account_number = EXCLUDED.bank_account_number,
  bank_name = EXCLUDED.bank_name,
  bank_code = EXCLUDED.bank_code,
  bank_address = EXCLUDED.bank_address,
  swift_code = EXCLUDED.swift_code,
  settlement_payment_term = EXCLUDED.settlement_payment_term,
  settlement_calculation_method = EXCLUDED.settlement_calculation_method,
  settlement_credit_days = EXCLUDED.settlement_credit_days,
  settlement_advance_payment_percentage = EXCLUDED.settlement_advance_payment_percentage,
  settlement_balance_trigger_event = EXCLUDED.settlement_balance_trigger_event,
  settlement_currency = EXCLUDED.settlement_currency,
  settlement_prepayment_pool = EXCLUDED.settlement_prepayment_pool,
  settlement_prepayment_threshold = EXCLUDED.settlement_prepayment_threshold,
  settlement_current_prepaid_balance = EXCLUDED.settlement_current_prepaid_balance,
  remark = EXCLUDED.remark,
  status = EXCLUDED.status,
  updated_at = EXCLUDED.updated_at;

COMMIT;

-- rows seeded: 3
