BEGIN;

INSERT INTO public.purchase_order_item (id, purchase_order_id, line_no, color, manufacture_date, machine_type, planned_qty, unit_price, operation_cost, settlement_price, line_amount, flp, lbx, locking_bars, vents, remark, created_at, updated_at, container_type_code_id, container_condition_code_id, container_size_code_id, location_city_id, depot_id, yom, offline_date, financial_cost, locking_bars_count, vents_count, tare_weight, maximum_weight, csc_number) VALUES ('49902ba7-c40d-4662-8842-33eef3843cec', (SELECT id FROM public.purchase_order WHERE order_no = 'POFDJ04191' LIMIT 1), 1, 'RAL1001', NULL, NULL, 1, 111.0, 0.0, 111.0, 111.0, true, true, false, false, NULL, '2026-04-19T01:17:46.158077+00:00', '2026-04-19T01:23:25.68408+00:00', (SELECT id FROM public.container_type_codes WHERE type_code = 'GP' LIMIT 1), (SELECT id FROM public.container_condition_codes WHERE condition_code = 'Brand New' LIMIT 1), (SELECT id FROM public.container_size_codes WHERE size_code = '20' LIMIT 1), (SELECT id FROM public.cities WHERE city_code = 'USLAX' LIMIT 1), (SELECT id FROM public.depots WHERE depot_code = 'USLAX001' LIMIT 1), 2026, NULL, 0.0, 3, 1, NULL, NULL, NULL);
INSERT INTO public.purchase_order_item (id, purchase_order_id, line_no, color, manufacture_date, machine_type, planned_qty, unit_price, operation_cost, settlement_price, line_amount, flp, lbx, locking_bars, vents, remark, created_at, updated_at, container_type_code_id, container_condition_code_id, container_size_code_id, location_city_id, depot_id, yom, offline_date, financial_cost, locking_bars_count, vents_count, tare_weight, maximum_weight, csc_number) VALUES ('7a101045-3869-4ce7-8582-6c58a23dc599', (SELECT id FROM public.purchase_order WHERE order_no = 'POFDJ04191' LIMIT 1), 2, 'RAL4011', NULL, NULL, 1, 222.0, 0.0, 222.0, 222.0, true, true, false, false, NULL, '2026-04-19T01:23:25.679236+00:00', '2026-04-19T01:23:25.688152+00:00', (SELECT id FROM public.container_type_codes WHERE type_code = 'DC Duocons' LIMIT 1), (SELECT id FROM public.container_condition_codes WHERE condition_code = 'Brand New' LIMIT 1), (SELECT id FROM public.container_size_codes WHERE size_code = '40' LIMIT 1), (SELECT id FROM public.cities WHERE city_code = 'USLAX' LIMIT 1), (SELECT id FROM public.depots WHERE depot_code = 'USLAX001' LIMIT 1), 2026, NULL, 0.0, 3, 2, NULL, NULL, NULL);
INSERT INTO public.purchase_order_item (id, purchase_order_id, line_no, color, manufacture_date, machine_type, planned_qty, unit_price, operation_cost, settlement_price, line_amount, flp, lbx, locking_bars, vents, remark, created_at, updated_at, container_type_code_id, container_condition_code_id, container_size_code_id, location_city_id, depot_id, yom, offline_date, financial_cost, locking_bars_count, vents_count, tare_weight, maximum_weight, csc_number) VALUES ('56aba2f6-0d36-41a6-b1d8-8c4f05ef7372', (SELECT id FROM public.purchase_order WHERE order_no = 'POFDJ04192' LIMIT 1), 1, 'RAL1015', NULL, NULL, 10, 1700.0, 0.0, 1700.0, 17000.0, true, true, false, false, NULL, '2026-04-19T00:24:31.157892+00:00', '2026-04-19T00:49:07.592723+00:00', (SELECT id FROM public.container_type_codes WHERE type_code = 'GP' LIMIT 1), (SELECT id FROM public.container_condition_codes WHERE condition_code = 'Brand New' LIMIT 1), (SELECT id FROM public.container_size_codes WHERE size_code = '20' LIMIT 1), (SELECT id FROM public.cities WHERE city_code = 'USLAX' LIMIT 1), (SELECT id FROM public.depots WHERE depot_code = 'USLAX001' LIMIT 1), 2026, NULL, 0.0, 3, 12, NULL, NULL, NULL);
INSERT INTO public.purchase_order_item (id, purchase_order_id, line_no, color, manufacture_date, machine_type, planned_qty, unit_price, operation_cost, settlement_price, line_amount, flp, lbx, locking_bars, vents, remark, created_at, updated_at, container_type_code_id, container_condition_code_id, container_size_code_id, location_city_id, depot_id, yom, offline_date, financial_cost, locking_bars_count, vents_count, tare_weight, maximum_weight, csc_number) VALUES ('8686a131-755f-4742-8b8d-e90eb71e50c6', (SELECT id FROM public.purchase_order WHERE order_no = 'POGED04191' LIMIT 1), 1, 'RAL1015', NULL, NULL, 2, 1000.0, 0.0, 1000.0, 2000.0, true, true, false, false, NULL, '2026-04-19T04:29:04.814188+00:00', '2026-04-19T04:29:04.814188+00:00', (SELECT id FROM public.container_type_codes WHERE type_code = 'GP' LIMIT 1), (SELECT id FROM public.container_condition_codes WHERE condition_code = 'Brand New' LIMIT 1), (SELECT id FROM public.container_size_codes WHERE size_code = '20' LIMIT 1), (SELECT id FROM public.cities WHERE city_code = 'USLAX' LIMIT 1), (SELECT id FROM public.depots WHERE depot_code = 'USLAX001' LIMIT 1), 2026, NULL, 0.0, 3, 9, NULL, NULL, NULL);
INSERT INTO public.purchase_order_item (id, purchase_order_id, line_no, color, manufacture_date, machine_type, planned_qty, unit_price, operation_cost, settlement_price, line_amount, flp, lbx, locking_bars, vents, remark, created_at, updated_at, container_type_code_id, container_condition_code_id, container_size_code_id, location_city_id, depot_id, yom, offline_date, financial_cost, locking_bars_count, vents_count, tare_weight, maximum_weight, csc_number) VALUES ('09363262-26a0-41e4-afcd-dd9a8af3ef99', (SELECT id FROM public.purchase_order WHERE order_no = 'POYFK04191' LIMIT 1), 1, 'RAL1001', NULL, NULL, 1, 2000.0, 0.0, 2000.0, 2000.0, true, true, false, false, NULL, '2026-04-19T04:30:32.849765+00:00', '2026-04-19T04:30:32.849765+00:00', (SELECT id FROM public.container_type_codes WHERE type_code = 'FR' LIMIT 1), (SELECT id FROM public.container_condition_codes WHERE condition_code = 'Brand New' LIMIT 1), (SELECT id FROM public.container_size_codes WHERE size_code = '20' LIMIT 1), (SELECT id FROM public.cities WHERE city_code = 'USLAX' LIMIT 1), (SELECT id FROM public.depots WHERE depot_code = 'USLAX001' LIMIT 1), 2026, NULL, 0.0, 3, 1, NULL, NULL, NULL);

COMMIT;

-- rows exported: 5
