BEGIN;

INSERT INTO public.lessees (
  id,
  lessee_code,
  legal_company_name,
  company_name,
  address,
  region_id,
  country,
  primary_contact_person,
  contact_email,
  contact_tel,
  pic_user_id,
  bank_account_name,
  bank_account_number,
  bank_name,
  bank_code,
  bank_address,
  swift_code,
  settlement_payment_term,
  settlement_credit_days,
  settlement_advance_payment_percentage,
  settlement_balance_trigger_event,
  settlement_currency,
  settlement_prepayment_pool,
  settlement_prepayment_threshold,
  settlement_current_prepaid_balance,
  remark,
  status,
  created_at,
  updated_at
) VALUES
  (
    '6291eb9e-3e69-4515-8f0a-bbded37f4001',
    'B7T9Q2',
    'BlueWave Leasing Pte. Ltd.',
    'BlueWave Leasing',
    '10 Anson Road, Singapore',
    (SELECT id FROM public.region_codes WHERE region_code = 'South-Asia' LIMIT 1),
    'Singapore',
    'Ethan Lim',
    'ops@bluewaveleasing.sg',
    '+65 6222 9001',
    '7a2b2ce8-e87a-4cc0-9165-52a6996fd701',
    'BlueWave Leasing Pte. Ltd.',
    '123-456-789-001',
    'DBS Bank',
    'DBSSG001',
    'Singapore',
    'DBSSSGSG',
    'Net 30',
    30,
    15.00,
    'On Invoice',
    'USD',
    true,
    25000.00,
    8600.00,
    'Primary leasing customer sample for page development.',
    'Normal',
    '2026-04-01T18:15:00+00:00',
    '2026-04-01T18:15:00+00:00'
  ),
  (
    '77c1cc22-54e5-4bfa-bc8c-6d5165cc4002',
    'B2M4R8',
    'Harbor Box Rental Inc.',
    'Harbor Box Rental',
    '175 Harbor Drive, Los Angeles, CA',
    (SELECT id FROM public.region_codes WHERE region_code = 'USA/CA' LIMIT 1),
    'United States',
    'Sophia Carter',
    'leasing@harborboxrental.com',
    '+1 213 555 0182',
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    'Net 15',
    15,
    0.00,
    'After Gate out',
    'USD',
    false,
    0.00,
    0.00,
    'Secondary lessee example with optional PIC empty.',
    'Blocked',
    '2026-04-01T18:16:00+00:00',
    '2026-04-01T18:16:00+00:00'
  )
ON CONFLICT (lessee_code) DO UPDATE
SET
  legal_company_name = EXCLUDED.legal_company_name,
  company_name = EXCLUDED.company_name,
  address = EXCLUDED.address,
  region_id = EXCLUDED.region_id,
  country = EXCLUDED.country,
  primary_contact_person = EXCLUDED.primary_contact_person,
  contact_email = EXCLUDED.contact_email,
  contact_tel = EXCLUDED.contact_tel,
  pic_user_id = EXCLUDED.pic_user_id,
  bank_account_name = EXCLUDED.bank_account_name,
  bank_account_number = EXCLUDED.bank_account_number,
  bank_name = EXCLUDED.bank_name,
  bank_code = EXCLUDED.bank_code,
  bank_address = EXCLUDED.bank_address,
  swift_code = EXCLUDED.swift_code,
  settlement_payment_term = EXCLUDED.settlement_payment_term,
  settlement_credit_days = EXCLUDED.settlement_credit_days,
  settlement_advance_payment_percentage = EXCLUDED.settlement_advance_payment_percentage,
  settlement_balance_trigger_event = EXCLUDED.settlement_balance_trigger_event,
  settlement_currency = EXCLUDED.settlement_currency,
  settlement_prepayment_pool = EXCLUDED.settlement_prepayment_pool,
  settlement_prepayment_threshold = EXCLUDED.settlement_prepayment_threshold,
  settlement_current_prepaid_balance = EXCLUDED.settlement_current_prepaid_balance,
  remark = EXCLUDED.remark,
  status = EXCLUDED.status,
  updated_at = EXCLUDED.updated_at;

COMMIT;

-- rows seeded: 2
