BEGIN;

INSERT INTO public.container_owners (
  id,
  container_owner_code,
  legal_company_name,
  company_name,
  address,
  region_id,
  country,
  primary_contact_person,
  contact_email,
  contact_tel,
  pic_user_id,
  bank_account_name,
  bank_account_number,
  bank_name,
  bank_code,
  bank_address,
  swift_code,
  settlement_payment_term,
  settlement_credit_days,
  settlement_advance_payment_percentage,
  settlement_balance_trigger_event,
  settlement_currency,
  settlement_prepayment_pool,
  settlement_prepayment_threshold,
  settlement_current_prepaid_balance,
  remark,
  status,
  created_at,
  updated_at
) VALUES
  (
    'd2aa003b-50c6-4912-bc04-79b965e57001',
    'O4K8M1',
    'OceanCore Equipment Holdings',
    'OceanCore',
    '1 Raffles Place, Singapore',
    (SELECT id FROM public.region_codes WHERE region_code = 'South-Asia' LIMIT 1),
    'Singapore',
    'Nadia Tan',
    'asset@oceancore.com',
    '+65 6333 2001',
    '7a2b2ce8-e87a-4cc0-9165-52a6996fd701',
    'OceanCore Equipment Holdings',
    '500123456789',
    'HSBC Singapore',
    'HSBCSG01',
    'Singapore',
    'HSBCSGSG',
    'Quarterly',
    45,
    25.00,
    'On Invoice',
    'USD',
    true,
    100000.00,
    78500.00,
    'Primary container owner used for development and testing.',
    'Normal',
    '2026-04-01T18:19:00+00:00',
    '2026-04-01T18:19:00+00:00'
  ),
  (
    '289fb682-1b21-44ce-90e7-178f82047002',
    'O9T3R6',
    'West Harbor Asset Management Ltd.',
    'West Harbor Assets',
    'Pier 9, Los Angeles',
    (SELECT id FROM public.region_codes WHERE region_code = 'USA/CA' LIMIT 1),
    'United States',
    'Daniel Green',
    'ops@westharborassets.com',
    '+1 310 555 1010',
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    'Net 30',
    30,
    0.00,
    'Before Release',
    'USD',
    false,
    0.00,
    0.00,
    'Secondary owner sample with nullable country/region-friendly structure.',
    'Blocked',
    '2026-04-01T18:20:00+00:00',
    '2026-04-01T18:20:00+00:00'
  )
ON CONFLICT (container_owner_code) DO UPDATE
SET
  legal_company_name = EXCLUDED.legal_company_name,
  company_name = EXCLUDED.company_name,
  address = EXCLUDED.address,
  region_id = EXCLUDED.region_id,
  country = EXCLUDED.country,
  primary_contact_person = EXCLUDED.primary_contact_person,
  contact_email = EXCLUDED.contact_email,
  contact_tel = EXCLUDED.contact_tel,
  pic_user_id = EXCLUDED.pic_user_id,
  bank_account_name = EXCLUDED.bank_account_name,
  bank_account_number = EXCLUDED.bank_account_number,
  bank_name = EXCLUDED.bank_name,
  bank_code = EXCLUDED.bank_code,
  bank_address = EXCLUDED.bank_address,
  swift_code = EXCLUDED.swift_code,
  settlement_payment_term = EXCLUDED.settlement_payment_term,
  settlement_credit_days = EXCLUDED.settlement_credit_days,
  settlement_advance_payment_percentage = EXCLUDED.settlement_advance_payment_percentage,
  settlement_balance_trigger_event = EXCLUDED.settlement_balance_trigger_event,
  settlement_currency = EXCLUDED.settlement_currency,
  settlement_prepayment_pool = EXCLUDED.settlement_prepayment_pool,
  settlement_prepayment_threshold = EXCLUDED.settlement_prepayment_threshold,
  settlement_current_prepaid_balance = EXCLUDED.settlement_current_prepaid_balance,
  remark = EXCLUDED.remark,
  status = EXCLUDED.status,
  updated_at = EXCLUDED.updated_at;

COMMIT;

-- rows seeded: 2
