BEGIN;

INSERT INTO public.vendors (
  id,
  vendor_code,
  legal_company_name,
  company_name,
  address,
  region_id,
  country,
  primary_contact_person,
  contact_email,
  contact_tel,
  category,
  assigned_buyer_id,
  bank_account_name,
  bank_account_number,
  bank_name,
  bank_code,
  bank_address,
  swift_code,
  settlement_payment_term,
  settlement_credit_days,
  settlement_advance_payment_percentage,
  settlement_balance_trigger_event,
  settlement_currency,
  settlement_prepayment_pool,
  settlement_prepayment_threshold,
  settlement_current_prepaid_balance,
  remark,
  status,
  created_at,
  updated_at
) VALUES
  (
    'f71328bf-fb55-4d43-8fd8-72e28b87d201',
    'S1A2B3',
    'Jiaxing XinhuaChang Containers Co., Ltd.',
    '新华昌',
    '185 Nanxing Road, Jiashan, Zhejiang, China',
    (SELECT id FROM public.region_codes WHERE region_code = 'China' LIMIT 1),
    'China',
    'Marissa Zhu',
    'marissa.zhu@xhcc.com',
    '+86 573 8463 3118',
    'Container',
    '7a2b2ce8-e87a-4cc0-9165-52a6996fd701',
    'JX XinhuaChang Containers',
    '6222021001112223334',
    'Bank of China Jiashan Branch',
    'BOCJS001',
    'No. 88 Renmin Avenue, Jiashan',
    'BKCHCNBJ92A',
    'Net 30',
    30,
    20.00,
    'After Gate out',
    'USD',
    true,
    50000.00,
    120000.00,
    'Primary production vendor for testing vendor workflows.',
    'Normal',
    '2026-04-01T18:05:00+00:00',
    '2026-04-01T18:05:00+00:00'
  ),
  (
    '2f6a9a61-5d65-4bf7-a0ab-6f429d6e2202',
    'S7K9M2',
    'Pacific Box Depot Supply LLC',
    'Pacific Box',
    '2400 Pacific Coast Highway, Wilmington, CA 90744, USA',
    (SELECT id FROM public.region_codes WHERE region_code = 'USA/CA' LIMIT 1),
    'United States',
    'Liset Cabrera',
    'ops@pacificboxdepot.com',
    '+1 562 435 3000',
    'Container',
    '9b2b0c18-0101-43f4-a5bf-8d9128eaa7c2',
    'Pacific Box Depot Supply LLC',
    '9876543210123456',
    'Citibank Los Angeles',
    'CITI-LAX-01',
    'Los Angeles, California',
    'CITIUS33',
    'Net 15',
    15,
    0.00,
    'Before Release',
    'USD',
    false,
    0.00,
    0.00,
    'Dealer-style vendor example for list and detail testing.',
    'Blocked',
    '2026-04-01T18:06:00+00:00',
    '2026-04-01T18:06:00+00:00'
  )
ON CONFLICT (vendor_code) DO UPDATE
SET
  legal_company_name = EXCLUDED.legal_company_name,
  company_name = EXCLUDED.company_name,
  address = EXCLUDED.address,
  region_id = EXCLUDED.region_id,
  country = EXCLUDED.country,
  primary_contact_person = EXCLUDED.primary_contact_person,
  contact_email = EXCLUDED.contact_email,
  contact_tel = EXCLUDED.contact_tel,
  category = EXCLUDED.category,
  assigned_buyer_id = EXCLUDED.assigned_buyer_id,
  bank_account_name = EXCLUDED.bank_account_name,
  bank_account_number = EXCLUDED.bank_account_number,
  bank_name = EXCLUDED.bank_name,
  bank_code = EXCLUDED.bank_code,
  bank_address = EXCLUDED.bank_address,
  swift_code = EXCLUDED.swift_code,
  settlement_payment_term = EXCLUDED.settlement_payment_term,
  settlement_credit_days = EXCLUDED.settlement_credit_days,
  settlement_advance_payment_percentage = EXCLUDED.settlement_advance_payment_percentage,
  settlement_balance_trigger_event = EXCLUDED.settlement_balance_trigger_event,
  settlement_currency = EXCLUDED.settlement_currency,
  settlement_prepayment_pool = EXCLUDED.settlement_prepayment_pool,
  settlement_prepayment_threshold = EXCLUDED.settlement_prepayment_threshold,
  settlement_current_prepaid_balance = EXCLUDED.settlement_current_prepaid_balance,
  remark = EXCLUDED.remark,
  status = EXCLUDED.status,
  updated_at = EXCLUDED.updated_at;

COMMIT;

-- rows seeded: 2
