BEGIN;

INSERT INTO public.depots (
    id,
    depot_code,
    depot_name,
    region,
    depot_type,
    working_hour,
    depot_address,
    contact_person,
    contact_email,
    account_email,
    depot_tel,
    currency,
    gate_in_out_cost,
    lift_in_out_cost,
    storage_rate_20,
    storage_rate_40,
    storage_rate_45,
    storage_rate_53,
    free_days,
    digging_cost,
    pti_cost,
    labour_cost,
    min_repair_cost,
    survey_cost,
    inspection_cost,
    est_recovery_fee,
    remark1,
    remark2,
    remark3,
    created_at,
    updated_at,
    city_id,
    region_id,
    status,
    depot_name_cn,
    depot_address_cn,
    fax,
    gate_email,
    country_code,
    country_name,
    gate_in_20_cost,
    gate_out_20_cost,
    gate_in_40_cost,
    gate_out_40_cost,
    lift_in_20_cost,
    lift_out_20_cost,
    lift_in_40_cost,
    lift_out_40_cost,
    user_return_surcharge_in,
    user_return_surcharge_out,
    settlement_cycle,
    payment_remark,
    other_terms_remark,
    business_contact_person,
    data_updated_on,
    remark,
    is_primary_depot,
    depot_attachment_url
) VALUES (
    'ce9ca9cb-3fbd-4646-a6fd-523c69b502f3',
    'USLAX001',
    'Fast Lane Transportation Inc',
    'USA/CA',
    'CONTRACT',
    NULL,
    '2400 E. Pacific Coast Highway, Wilmington, CA 90744',
    'Liset Cabrera',
    'owner@fastlanetrans.com',
    NULL,
    '562-435-3000',
    'USD',
    0.00,
    0.00,
    0.00,
    0.00,
    0.00,
    0.00,
    0,
    0.00,
    0.00,
    0.00,
    0.00,
    0.00,
    0.00,
    0.00,
    NULL,
    NULL,
    NULL,
    '2026-03-30T23:59:00+00:00',
    '2026-03-30T23:59:00+00:00',
    (SELECT id FROM public.cities WHERE city_code = 'USLAX' LIMIT 1),
    (SELECT region_id FROM public.cities WHERE city_code = 'USLAX' LIMIT 1),
    'NORMAL',
    'Fast Lane Transportation Inc',
    NULL,
    NULL,
    'flt@fastlanetrans.com',
    'US',
    'United States',
    0.00,
    0.00,
    0.00,
    0.00,
    0.00,
    0.00,
    0.00,
    0.00,
    0.00,
    0.00,
    NULL,
    NULL,
    NULL,
    NULL,
    '2026-03-30',
    'Seeded default depot for local development.',
    true,
    NULL
)
ON CONFLICT (id) DO UPDATE SET
    depot_code = EXCLUDED.depot_code,
    depot_name = EXCLUDED.depot_name,
    region = EXCLUDED.region,
    depot_type = EXCLUDED.depot_type,
    depot_address = EXCLUDED.depot_address,
    contact_person = EXCLUDED.contact_person,
    contact_email = EXCLUDED.contact_email,
    depot_tel = EXCLUDED.depot_tel,
    currency = EXCLUDED.currency,
    city_id = EXCLUDED.city_id,
    region_id = EXCLUDED.region_id,
    status = EXCLUDED.status,
    depot_name_cn = EXCLUDED.depot_name_cn,
    gate_email = EXCLUDED.gate_email,
    country_code = EXCLUDED.country_code,
    country_name = EXCLUDED.country_name,
    data_updated_on = EXCLUDED.data_updated_on,
    remark = EXCLUDED.remark,
    is_primary_depot = EXCLUDED.is_primary_depot,
    updated_at = EXCLUDED.updated_at;

INSERT INTO public.depot_attachment_links (
    id,
    depot_id,
    url,
    created_at,
    updated_at
) VALUES (
    '7e3d0192-c7de-4d9e-8d8d-04e738d64af0',
    'ce9ca9cb-3fbd-4646-a6fd-523c69b502f3',
    'https://ewlogisticsco-my.sharepoint.com/:b:/g/personal/wesley_ew-logistics_com/IQBYQIBQJfw2QI-VFyalykxwARIB4eWplfOsyjXJOzWEImk',
    '2026-03-30T23:59:00+00:00',
    '2026-03-30T23:59:00+00:00'
)
ON CONFLICT (id) DO UPDATE SET
    url = EXCLUDED.url,
    updated_at = EXCLUDED.updated_at;

COMMIT;

-- rows seeded: 1 depot, 1 attachment
