BEGIN;

DELETE FROM public.container_type_codes;

INSERT INTO public.container_type_codes (id, type_code, type_description, remark, status) VALUES ('4243d99e-7fca-4c24-bb95-64de52da0408', 'GP', 'GP', '标准柜', 'ACTIVE') ON CONFLICT (type_code) DO UPDATE SET type_description = EXCLUDED.type_description, remark = EXCLUDED.remark, status = EXCLUDED.status;
INSERT INTO public.container_type_codes (id, type_code, type_description, remark, status) VALUES ('78d25506-fa49-4a67-8383-5578d231a2be', 'HQ', 'HQ', '高柜', 'ACTIVE') ON CONFLICT (type_code) DO UPDATE SET type_description = EXCLUDED.type_description, remark = EXCLUDED.remark, status = EXCLUDED.status;
INSERT INTO public.container_type_codes (id, type_code, type_description, remark, status) VALUES ('aa130f0c-e403-4c1a-8d50-02826bc6e02b', 'RF', 'Reefer Standard', '标准柜冷藏集装箱', 'ACTIVE') ON CONFLICT (type_code) DO UPDATE SET type_description = EXCLUDED.type_description, remark = EXCLUDED.remark, status = EXCLUDED.status;
INSERT INTO public.container_type_codes (id, type_code, type_description, remark, status) VALUES ('78d1b161-d889-4b74-87a6-22d782271469', 'RH', 'High Cube Reefer', '高柜冷藏集装箱', 'ACTIVE') ON CONFLICT (type_code) DO UPDATE SET type_description = EXCLUDED.type_description, remark = EXCLUDED.remark, status = EXCLUDED.status;
INSERT INTO public.container_type_codes (id, type_code, type_description, remark, status) VALUES ('4abbc232-8433-48a3-81d8-696256e4a7d5', 'OT', 'Open Top', '开顶集装箱', 'ACTIVE') ON CONFLICT (type_code) DO UPDATE SET type_description = EXCLUDED.type_description, remark = EXCLUDED.remark, status = EXCLUDED.status;
INSERT INTO public.container_type_codes (id, type_code, type_description, remark, status) VALUES ('73c56abe-9154-4783-a2d0-094f572e61dd', 'FR', 'Flat Rack', '框架集装箱', 'ACTIVE') ON CONFLICT (type_code) DO UPDATE SET type_description = EXCLUDED.type_description, remark = EXCLUDED.remark, status = EXCLUDED.status;
INSERT INTO public.container_type_codes (id, type_code, type_description, remark, status) VALUES ('1ca92667-62d7-4f7a-b809-7c80a5a6a29a', 'Tank', 'Tank', '罐式集装箱', 'ACTIVE') ON CONFLICT (type_code) DO UPDATE SET type_description = EXCLUDED.type_description, remark = EXCLUDED.remark, status = EXCLUDED.status;
INSERT INTO public.container_type_codes (id, type_code, type_description, remark, status) VALUES ('8358c918-92d9-4b7a-9481-4a1b28696a32', 'GP3', 'GP Tri-Door', '三开门标准柜集装箱', 'ACTIVE') ON CONFLICT (type_code) DO UPDATE SET type_description = EXCLUDED.type_description, remark = EXCLUDED.remark, status = EXCLUDED.status;
INSERT INTO public.container_type_codes (id, type_code, type_description, remark, status) VALUES ('7587100a-5775-4576-a36d-75097a74403f', 'HQ3', 'HQ Tri-Door', '三开门高柜集装箱', 'ACTIVE') ON CONFLICT (type_code) DO UPDATE SET type_description = EXCLUDED.type_description, remark = EXCLUDED.remark, status = EXCLUDED.status;
INSERT INTO public.container_type_codes (id, type_code, type_description, remark, status) VALUES ('3b24c952-fe47-487b-99e0-eb612bb276cc', 'GPDD', 'GP Double Door', '双端开门标准柜', 'ACTIVE') ON CONFLICT (type_code) DO UPDATE SET type_description = EXCLUDED.type_description, remark = EXCLUDED.remark, status = EXCLUDED.status;
INSERT INTO public.container_type_codes (id, type_code, type_description, remark, status) VALUES ('781e8419-0405-4b15-918b-b445ea0547fd', 'HCDD', 'HC Double Door', '双端开门高柜', 'ACTIVE') ON CONFLICT (type_code) DO UPDATE SET type_description = EXCLUDED.type_description, remark = EXCLUDED.remark, status = EXCLUDED.status;
INSERT INTO public.container_type_codes (id, type_code, type_description, remark, status) VALUES ('da8142e0-bd19-4fcd-8f22-b93d29f1aa0d', 'HCOS', 'HCOS (4 side doors)', '高柜单侧开门四门集装箱', 'ACTIVE') ON CONFLICT (type_code) DO UPDATE SET type_description = EXCLUDED.type_description, remark = EXCLUDED.remark, status = EXCLUDED.status;
INSERT INTO public.container_type_codes (id, type_code, type_description, remark, status) VALUES ('1e95f00a-9c1a-48cb-8172-a72348ad1d1d', 'HCFOS', 'HCOS (full open)', '高柜全侧开门集装箱', 'ACTIVE') ON CONFLICT (type_code) DO UPDATE SET type_description = EXCLUDED.type_description, remark = EXCLUDED.remark, status = EXCLUDED.status;
INSERT INTO public.container_type_codes (id, type_code, type_description, remark, status) VALUES ('f52c2de3-0b82-4cbc-be57-4d8c79014c32', 'GPHOT', 'GPHOT (half open top)', '半开顶标准柜集装箱', 'ACTIVE') ON CONFLICT (type_code) DO UPDATE SET type_description = EXCLUDED.type_description, remark = EXCLUDED.remark, status = EXCLUDED.status;
INSERT INTO public.container_type_codes (id, type_code, type_description, remark, status) VALUES ('0108c9b2-d2e2-4b27-a22f-a6612edf19d4', 'HCHOT', 'HCHOT (half open top)', '半开顶高柜集装箱', 'ACTIVE') ON CONFLICT (type_code) DO UPDATE SET type_description = EXCLUDED.type_description, remark = EXCLUDED.remark, status = EXCLUDED.status;
INSERT INTO public.container_type_codes (id, type_code, type_description, remark, status) VALUES ('cb6bd142-a05a-468b-be7a-cfb1a7eb208a', 'DC Duocons', 'DC Duocons', '标准柜组合柜', 'ACTIVE') ON CONFLICT (type_code) DO UPDATE SET type_description = EXCLUDED.type_description, remark = EXCLUDED.remark, status = EXCLUDED.status;
INSERT INTO public.container_type_codes (id, type_code, type_description, remark, status) VALUES ('466a8729-1ae3-4dc2-9862-f0a690096d7a', 'HC Duocons', 'HC Duocons', '高柜组合柜', 'ACTIVE') ON CONFLICT (type_code) DO UPDATE SET type_description = EXCLUDED.type_description, remark = EXCLUDED.remark, status = EXCLUDED.status;
INSERT INTO public.container_type_codes (id, type_code, type_description, remark, status) VALUES ('188607cf-a629-476a-8aff-a2d3c351fb69', 'GS', 'Gensets', '发电机组 (供冷藏箱使用)', 'ACTIVE') ON CONFLICT (type_code) DO UPDATE SET type_description = EXCLUDED.type_description, remark = EXCLUDED.remark, status = EXCLUDED.status;
INSERT INTO public.container_type_codes (id, type_code, type_description, remark, status) VALUES ('c5a9819f-1a64-4307-a855-f9ed582bd6c2', 'TK', 'Thermo King Machine', '制冷机组 (特指机头设备)', 'ACTIVE') ON CONFLICT (type_code) DO UPDATE SET type_description = EXCLUDED.type_description, remark = EXCLUDED.remark, status = EXCLUDED.status;
INSERT INTO public.container_type_codes (id, type_code, type_description, remark, status) VALUES ('eb50ad53-b4b5-4acb-9bab-6ea5197277a2', 'OS', 'Open Side (full open)', '标准柜全侧开集装箱', 'ACTIVE') ON CONFLICT (type_code) DO UPDATE SET type_description = EXCLUDED.type_description, remark = EXCLUDED.remark, status = EXCLUDED.status;
INSERT INTO public.container_type_codes (id, type_code, type_description, remark, status) VALUES ('bcb4a736-8902-4252-b6a1-e168d9c219ac', 'OS2', 'Open Side (2 side doors)', '标准柜两门侧开集装箱', 'ACTIVE') ON CONFLICT (type_code) DO UPDATE SET type_description = EXCLUDED.type_description, remark = EXCLUDED.remark, status = EXCLUDED.status;

COMMIT;

-- rows exported: 21
